# Generated by Django 6.0.1 on 2026-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('template_key', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
