# Generated by Django 6.0.1 on 2026-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='کد رویداد')),
                ('label', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('send_mode', models.CharField(choices=[('custom', 'متن دلخواه'), ('template', 'قالب sms.ir')], default='custom', max_length=10, verbose_name='روش ارسال')),
                ('custom_text', models.TextField(blank=True, help_text='می\u200cتوانید از پارامترهای این رویداد به شکل {نام_پارامتر} استفاده کنید.', verbose_name='متن دلخواه')),
                ('template_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه قالب sms.ir')),
                ('parameter_mapping', models.JSONField(blank=True, default=dict, help_text='نگاشت نام داخلی هر پارامتر به نام همان پارامتر در قالب sms.ir.', verbose_name='نگاشت پارامترها')),
            ],
            options={
                'verbose_name': 'رویداد پیامکی',
                'verbose_name_plural': 'رویدادهای پیامکی',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SmsProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('smsir', 'sms.ir')], default='smsir', max_length=20, verbose_name='سامانه پیامکی')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API')),
                ('default_line_number', models.CharField(blank=True, max_length=20, verbose_name='شماره خط پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سامانه پیامکی',
                'verbose_name_plural': 'تنظیمات سامانه\u200cهای پیامکی',
            },
        ),
    ]
