# Generated by Django 6.0.1 on 2026-09-14 10:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_sms_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsevent',
            name='parameter_mapping',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='نگاشت نام داخلی هر پارامتر به نام همان پارامتر در قالب sms.ir.', verbose_name='نگاشت پارامترها'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='parameters',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='response_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
