# Generated by Django 6.0.1 on 2026-06-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwarderCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_type', models.CharField(choices=[('private_joint_stock', 'سهامی خاص'), ('public_joint_stock', 'سهامی عام'), ('limited_liability', 'مسئولیت محدود'), ('cooperative', 'تعاونی'), ('general_partnership', 'تضامنی'), ('other', 'سایر')], max_length=30)),
                ('national_id', models.CharField(max_length=11, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('ceo_first_name', models.CharField(max_length=100)),
                ('ceo_last_name', models.CharField(max_length=100)),
                ('ceo_national_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='forwarder_logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.OneToOneField(limit_choices_to={'role': 'forwarder_admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='forwarder_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شرکت فورواردر',
                'verbose_name_plural': 'شرکت\u200cهای فورواردر',
            },
        ),
        migrations.CreateModel(
            name='ForwarderBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('representative_first_name', models.CharField(max_length=100)),
                ('representative_last_name', models.CharField(max_length=100)),
                ('representative_mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forwarder_branch', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.province')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='forwarders.forwardercompany')),
            ],
            options={
                'verbose_name': 'شعبه فورواردر',
                'verbose_name_plural': 'شعب فورواردر',
            },
        ),
        migrations.CreateModel(
            name='ForwarderStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='forwarders.forwardercompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forwarder_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارمند فورواردر',
                'verbose_name_plural': 'کارمندان فورواردر',
            },
        ),
    ]
