# Generated by Django 6.0.1 on 2026-06-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardercompany',
            name='company_name',
            field=models.CharField(default=2, max_length=255, verbose_name='نام شرکت'),
            preserve_default=False,
        ),
    ]
