# Generated by Django 6.0.1 on 2026-06-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0002_forwardercompany_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwarderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام نقش')),
                ('can_view_orders', models.BooleanField(default=False, verbose_name='مشاهده سفارشات')),
                ('can_manage_orders', models.BooleanField(default=False, verbose_name='مدیریت سفارشات')),
                ('can_update_order_status', models.BooleanField(default=False, verbose_name='تغییر وضعیت سفارش')),
                ('can_send_order_message', models.BooleanField(default=False, verbose_name='ارسال پیام در سفارش')),
                ('can_request_documents', models.BooleanField(default=False, verbose_name='درخواست مدارک از مشتری')),
                ('can_view_rates', models.BooleanField(default=False, verbose_name='مشاهده نرخ\u200cها')),
                ('can_create_rates', models.BooleanField(default=False, verbose_name='ایجاد نرخ جدید')),
                ('can_edit_rates', models.BooleanField(default=False, verbose_name='ویرایش نرخ\u200cها')),
                ('can_delete_rates', models.BooleanField(default=False, verbose_name='حذف نرخ\u200cها')),
                ('can_bulk_upload_rates', models.BooleanField(default=False, verbose_name='آپلود گروهی نرخ')),
                ('can_view_branches', models.BooleanField(default=False, verbose_name='مشاهده شعب')),
                ('can_manage_branches', models.BooleanField(default=False, verbose_name='مدیریت شعب')),
                ('can_view_staff', models.BooleanField(default=False, verbose_name='مشاهده کارمندان')),
                ('can_manage_staff', models.BooleanField(default=False, verbose_name='مدیریت کارمندان')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='مشاهده گزارشات')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='خروجی گرفتن از گزارشات')),
                ('can_view_documents', models.BooleanField(default=False, verbose_name='مشاهده مدارک')),
                ('can_manage_documents', models.BooleanField(default=False, verbose_name='تایید/رد مدارک')),
                ('can_view_support', models.BooleanField(default=False, verbose_name='مشاهده تیکت\u200cهای پشتیبانی')),
                ('can_reply_support', models.BooleanField(default=False, verbose_name='پاسخ به تیکت\u200cهای پشتیبانی')),
                ('can_view_settings', models.BooleanField(default=False, verbose_name='مشاهده تنظیمات')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='مدیریت نقش\u200cها و دسترسی\u200cها')),
                ('can_upload_logo', models.BooleanField(default=False, verbose_name='آپلود لوگو شرکت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='forwarders.forwardercompany')),
            ],
            options={
                'verbose_name': 'نقش فورواردر',
                'verbose_name_plural': 'نقش\u200cهای فورواردر',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
