# Generated by Django 6.0.1 on 2026-06-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0003_forwarderrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwarderstaff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='forwarderstaff',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='forwarderstaff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='forwarders.forwarderrole', verbose_name='نقش'),
        ),
    ]
