# Generated by Django 6.0.1 on 2026-06-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('platform_admin', 'ادمین پلتفرم'), ('customer', 'مشتری'), ('forwarder_admin', 'ادمین فورواردر'), ('forwarder_expert', 'کارشناس فورواردر'), ('forwarder_finance', 'کارمند مالی فورواردر')], default='customer', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='CustomerBusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('usual_cargo_type', models.CharField(blank=True, max_length=200)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.OneToOneField(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعات تجاری مشتری',
                'verbose_name_plural': 'اطلاعات تجاری مشتریان',
            },
        ),
        migrations.CreateModel(
            name='CustomerCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_type', models.CharField(choices=[('private_joint_stock', 'سهامی خاص'), ('public_joint_stock', 'سهامی عام'), ('limited_liability', 'مسئولیت محدود'), ('cooperative', 'تعاونی'), ('general_partnership', 'تضامنی'), ('other', 'سایر')], max_length=30)),
                ('national_id', models.CharField(max_length=11, unique=True, verbose_name='شناسه ملی شرکت')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('ceo_first_name', models.CharField(max_length=100)),
                ('ceo_last_name', models.CharField(max_length=100)),
                ('ceo_national_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مشتری حقوقی',
                'verbose_name_plural': 'پروفایل\u200cهای مشتری حقوقی',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مشتری حقیقی',
                'verbose_name_plural': 'پروفایل\u200cهای مشتری حقیقی',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('national_card', 'کارت ملی'), ('birth_certificate', 'شناسنامه'), ('establishment_notice', 'آگهی تاسیس'), ('articles_of_association', 'اساسنامه'), ('ceo_national_card', 'کارت ملی مدیر عامل')], max_length=30)),
                ('file', models.FileField(upload_to='identity_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مدرک هویتی',
                'verbose_name_plural': 'مدارک هویتی',
            },
        ),
    ]
