# Generated by Django 6.0.1 on 2026-06-13 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('purpose', models.CharField(choices=[('register', 'ثبت\u200cنام'), ('login', 'ورود'), ('password_reset', 'فراموشی رمز عبور')], max_length=30)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_count', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'کد تایید پیامکی',
                'verbose_name_plural': 'کدهای تایید پیامکی',
                'indexes': [models.Index(fields=['mobile', 'purpose', 'is_used'], name='accounts_ot_mobile_0296d9_idx')],
            },
        ),
    ]
