# Generated by Django 6.0.1 on 2026-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['mobile', 'purpose', 'created_at'], name='accounts_ot_mobile_6a0c63_idx'),
        ),
    ]
