# Generated by Django 6.0.1 on 2026-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode_accounts_ot_mobile_6a0c63_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'کد یکبار مصرف', 'verbose_name_plural': 'کدهای یکبار مصرف'},
        ),
        migrations.RemoveIndex(
            model_name='otpcode',
            name='accounts_ot_mobile_6a0c63_idx',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'ثبت\u200cنام'), ('login', 'ورود'), ('password_reset', 'فراموشی رمز عبور')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_2f08f4_idx'),
        ),
    ]
