# Generated by Django 6.0.1 on 2026-06-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otpcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='doc_type',
            field=models.CharField(choices=[('national_card', 'کارت ملی نماینده'), ('birth_certificate', 'شناسنامه'), ('establishment_notice', 'آگهی تاسیس'), ('articles_of_association', 'اساسنامه'), ('latest_changes', 'آخرین تغییرات روزنامه رسمی'), ('ceo_national_card', 'کارت ملی مدیر عامل')], max_length=30),
        ),
    ]
