# Generated by Django 6.0.1 on 2026-06-14 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_identitydocument_doc_type'),
        ('forwarders', '0002_forwardercompany_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='forwarders.forwardercompany', verbose_name='شرکت فورواردر'),
        ),
    ]
