# Generated by Django 6.0.1 on 2026-06-14 14:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_identitydocument_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='file',
            field=models.FileField(upload_to=accounts.models.identity_document_upload_to),
        ),
    ]
