# Generated by Django 6.0.1 on 2026-06-22 01:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_identitydocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, validators=[core.validators.validate_iranian_national_code], verbose_name='کد ملی'),
        ),
    ]
