# Generated by Django 6.0.1 on 2026-09-13 21:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[core.validators.validate_iranian_national_code], verbose_name='کد ملی'),
        ),
    ]
