# Generated by Django 6.0.1 on 2026-09-14 08:40

import accounts.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customerprofile_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='file',
            field=models.FileField(storage=core.storage.protected_storage, upload_to=accounts.models.identity_document_upload_to),
        ),
    ]
