# Generated by Django 6.0.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_identitydocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'ادمین پلتفرم'), ('customer', 'مشتری'), ('forwarder_admin', 'ادمین فورواردر'), ('forwarder_expert', 'کارشناس فورواردر'), ('forwarder_finance', 'کارمند مالی فورواردر')], db_index=True, default='customer', max_length=30),
        ),
    ]
