# Generated by Django 6.0.1 on 2026-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportdepartment',
            name='panel_type',
            field=models.CharField(choices=[('forwarder', 'فورواردر'), ('customer', 'مشتری')], default='customer', max_length=20),
        ),
    ]
