# Generated by Django 6.0.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportdepartment_panel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('pending', 'در انتظار کاربر'), ('answered', 'پاسخ داده شد'), ('closed', 'بسته شد')], db_index=True, default='open', max_length=20),
        ),
    ]
