# Generated by Django 6.0.1 on 2026-06-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('air', 'هوایی'), ('sea_fcl', 'دریایی FCL'), ('sea_lcl', 'دریایی LCL'), ('land_rail', 'زمینی / ریلی')], max_length=20, verbose_name='روش حمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_rates', to='locations.destinationcity', verbose_name='شهر مقصد')),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_rates', to='locations.country', verbose_name='کشور مقصد')),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_rates', to='locations.port', verbose_name='پورت/فرودگاه مقصد')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_rates', to='locations.city', verbose_name='شهر مبدا')),
                ('origin_province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_rates', to='locations.province', verbose_name='استان مبدا')),
            ],
            options={
                'verbose_name': 'نرخ پایه',
                'verbose_name_plural': 'نرخ\u200cهای پایه',
            },
        ),
        migrations.CreateModel(
            name='RateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_unit', models.CharField(choices=[('fixed', 'نرخ ثابت (Fixed)'), ('per_kg', 'به ازای هر کیلوگرم (Per KG)'), ('per_container', 'به ازای هر کانتینر (Per Container)')], max_length=20, verbose_name='واحد قیمت\u200cگذاری')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('weight_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='از وزن (KG)')),
                ('weight_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تا وزن (KG)')),
                ('container_size', models.CharField(blank=True, choices=[('20ft', '۲۰ فوت'), ('40ft_std', '۴۰ فوت استاندارد'), ('40ft_hc', '۴۰ فوت های\u200cکیوب'), ('45ft_hc', '۴۵ فوت های\u200cکیوب')], max_length=20, null=True, verbose_name='ابعاد کانتینر')),
                ('container_type', models.CharField(blank=True, choices=[('dry', 'خشک استاندارد'), ('reefer', 'یخچالی'), ('open_top', 'روباز از بالا'), ('flat_rack', 'تخت'), ('platform', 'پلتفرم'), ('tank', 'تانکی'), ('ventilated', 'دارای تهویه'), ('insulated', 'عایق\u200cبندی\u200cشده'), ('double_door', 'دو درب')], max_length=20, null=True, verbose_name='نوع کانتینر')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='rates.rate', verbose_name='نرخ مرتبط')),
            ],
            options={
                'verbose_name': 'ردیف قیمتی',
                'verbose_name_plural': 'ردیف\u200cهای قیمتی',
            },
        ),
    ]
