# Generated by Django 6.0.1 on 2026-06-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarders', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='forwarders.forwarderbranch', verbose_name='شعبه فورواردر'),
        ),
        migrations.AddField(
            model_name='rate',
            name='forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='forwarders.forwardercompany', verbose_name='شرکت فورواردر'),
        ),
    ]
