# Generated by Django 6.0.1 on 2026-06-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_rate_branch_rate_forwarder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال بودن'),
        ),
        migrations.AddField(
            model_name='rate',
            name='valid_until',
            field=models.DateField(default='2026-12-31', verbose_name='تاریخ اعتبار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='transport_mode',
            field=models.CharField(choices=[('air', 'هوایی'), ('sea_fcl', 'دریایی FCL'), ('sea_lcl', 'دریایی LCL'), ('land', 'زمینی'), ('rail', 'ریلی')], max_length=20, verbose_name='روش حمل'),
        ),
    ]
