# Generated by Django 6.0.1 on 2026-06-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_rate_is_active_rate_valid_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان کالا')),
                ('transport_mode', models.CharField(choices=[('air', 'هوایی'), ('sea_fcl', 'دریایی FCL'), ('sea_lcl', 'دریایی LCL'), ('land', 'زمینی'), ('rail', 'ریلی')], max_length=20, verbose_name='وابسته به روش حمل')),
            ],
            options={
                'verbose_name': 'نوع کالا',
                'verbose_name_plural': 'انواع کالا',
            },
        ),
    ]
