# Generated by Django 6.0.1 on 2026-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_cargotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='cargo_types',
            field=models.ManyToManyField(blank=True, related_name='rates', to='rates.cargotype', verbose_name='نوع کالا'),
        ),
    ]
