# Generated by Django 6.0.1 on 2026-06-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_rate_cargo_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargotype',
            options={'verbose_name': 'نوع کالا (دسته اصلی)', 'verbose_name_plural': 'انواع کالا (دسته\u200cهای اصلی)'},
        ),
        migrations.AlterField(
            model_name='cargotype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان دسته اصلی کالا'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='cargo_types',
            field=models.ManyToManyField(blank=True, related_name='rates', to='rates.cargotype', verbose_name='نوع کالا (دسته\u200cهای تحت پوشش)'),
        ),
        migrations.CreateModel(
            name='CargoSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان زیردسته')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='rates.cargotype', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'زیردسته کالا',
                'verbose_name_plural': 'زیردسته\u200cهای کالا',
            },
        ),
    ]
