# Generated by Django 6.0.1 on 2026-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_alter_cargotype_options_alter_cargotype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargosubcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
