# Generated by Django 6.0.1 on 2026-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_cargosubcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='shipping_procedure',
            field=models.CharField(choices=[('passenger', 'مسافری'), ('commercial', 'تجاری')], default='commercial', max_length=20, verbose_name='رویه ارسال'),
        ),
    ]
