# Generated by Django 6.0.1 on 2026-06-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_province_country'),
        ('rates', '0008_rate_shipping_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_rates', to='locations.country', verbose_name='کشور مبدا'),
        ),
    ]
