# Generated by Django 6.0.1 on 2026-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0009_rate_origin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='add_vat',
            field=models.BooleanField(default=False, verbose_name='افزودن ۱۰٪ ارزش افزوده به نرخ\u200cها'),
        ),
        migrations.AddField(
            model_name='rate',
            name='doorstep_packaging_charge_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='free', max_length=20, verbose_name='نوع هزینه تحویل و بسته\u200cبندی درب محل'),
        ),
        migrations.AddField(
            model_name='rate',
            name='doorstep_packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ تحویل و بسته\u200cبندی درب محل'),
        ),
        migrations.AddField(
            model_name='rate',
            name='packaging_charge_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='free', max_length=20, verbose_name='نوع هزینه بسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='rate',
            name='packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ بسته\u200cبندی'),
        ),
    ]
