# Generated by Django 6.0.1 on 2026-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0010_rate_add_vat_rate_doorstep_packaging_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='doorstep_packaging_charge_type',
            field=models.CharField(choices=[('not_available', 'ارائه نمی\u200cشود'), ('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='not_available', max_length=20, verbose_name='نوع هزینه تحویل و بسته\u200cبندی درب محل'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='packaging_charge_type',
            field=models.CharField(choices=[('not_available', 'ارائه نمی\u200cشود'), ('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='not_available', max_length=20, verbose_name='نوع هزینه بسته\u200cبندی'),
        ),
    ]
