# Generated by Django 6.0.1 on 2026-06-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0011_alter_rate_doorstep_packaging_charge_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='packaging_charge_type',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='packaging_price',
        ),
        migrations.AddField(
            model_name='rate',
            name='office_packaging_charge_type',
            field=models.CharField(choices=[('not_available', 'ارائه نمی\u200cشود'), ('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='not_available', max_length=20, verbose_name='نوع هزینه بسته\u200cبندی در دفتر'),
        ),
        migrations.AddField(
            model_name='rate',
            name='office_packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ بسته\u200cبندی در دفتر'),
        ),
        migrations.AddField(
            model_name='rate',
            name='onsite_packaging_charge_type',
            field=models.CharField(choices=[('not_available', 'ارائه نمی\u200cشود'), ('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='not_available', max_length=20, verbose_name='نوع هزینه بسته\u200cبندی در محل'),
        ),
        migrations.AddField(
            model_name='rate',
            name='onsite_packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ بسته\u200cبندی در محل'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='doorstep_packaging_charge_type',
            field=models.CharField(choices=[('not_available', 'ارائه نمی\u200cشود'), ('free', 'رایگان'), ('fixed', 'هزینه ثابت'), ('per_kg', 'به ازای هر کیلوگرم')], default='not_available', max_length=20, verbose_name='نوع هزینه تحویل  درب محل'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='doorstep_packaging_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ تحویل  درب محل'),
        ),
        migrations.AlterField(
            model_name='ratetier',
            name='container_size',
            field=models.CharField(blank=True, choices=[('20ft', '۲۰ فوت'), ('40ft_std', '۴۰ فوت استاندارد'), ('40ft_hc', '۴۰ فوت های\u200cکیوب'), ('45ft_hc', '۴۵ فوت های\u200cکیوب')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratetier',
            name='container_type',
            field=models.CharField(blank=True, choices=[('dry', 'خشک استاندارد'), ('reefer', 'یخچالی'), ('open_top', 'روباز از بالا'), ('flat_rack', 'تخت'), ('platform', 'پلتفرم'), ('tank', 'تانکی'), ('ventilated', 'دارای تهویه'), ('insulated', 'عایق\u200cبندی\u200cشده'), ('double_door', 'دو درب')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratetier',
            name='weight_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ratetier',
            name='weight_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
