# Generated by Django 6.0.1 on 2026-06-22 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0012_remove_rate_packaging_charge_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoSubCategoryChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان فرزند زیردسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rates.cargosubcategory', verbose_name='زیردسته والد')),
            ],
            options={
                'verbose_name': 'فرزند زیردسته کالا',
                'verbose_name_plural': 'فرزندهای زیردسته کالا',
            },
        ),
    ]
