# Generated by Django 6.0.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0013_cargosubcategorychild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وضعیت فعال بودن'),
        ),
    ]
