# Generated by Django 6.0.1 on 2026-06-15 11:57

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_alter_port_port_type'),
        ('orders', '0005_cargorequest_shipping_procedure'),
        ('rates', '0007_cargosubcategory_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مدرک')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='کد یکتا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('allowed_extensions', models.CharField(default='pdf,jpg,jpeg,png', help_text='با کاما جدا شود. مثال: pdf,jpg,png', max_length=255, verbose_name='پسوندهای مجاز')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, verbose_name='حداکثر حجم فایل بر حسب مگابایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع مدرک',
                'verbose_name_plural': 'انواع مدارک',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درخواست')),
                ('description', models.TextField(verbose_name='توضیحات برای مشتری')),
                ('custom_document_title', models.CharField(blank=True, help_text='اگر نوع مدرک از لیست انتخاب نشده، این فیلد پر شود.', max_length=255, verbose_name='عنوان مدرک سفارشی')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن لینک')),
                ('status', models.CharField(choices=[('open', 'باز'), ('completed', 'تکمیل شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='open', max_length=30, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیامک')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document_requests', to='orders.cargorequest', verbose_name='سفارش')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_additional_document_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_requests', to='documents.documenttype', verbose_name='نوع مدرک')),
            ],
            options={
                'verbose_name': 'درخواست مدرک تکمیلی',
                'verbose_name_plural': 'درخواست\u200cهای مدارک تکمیلی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=documents.models.additional_document_upload_to, verbose_name='فایل')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیح مشتری')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='documents.additionaldocumentrequest', verbose_name='درخواست')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_document_uploads', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'فایل مدرک تکمیلی',
                'verbose_name_plural': 'فایل\u200cهای مدارک تکمیلی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان قانون')),
                ('shipping_procedure', models.CharField(blank=True, choices=[('passenger', 'مسافری'), ('commercial', 'تجاری')], max_length=20, null=True, verbose_name='رویه ارسال')),
                ('transport_mode', models.CharField(blank=True, choices=[('air', 'هوایی'), ('sea_fcl', 'دریایی FCL'), ('sea_lcl', 'دریایی LCL'), ('land', 'زمینی'), ('rail', 'ریلی')], max_length=20, null=True, verbose_name='روش حمل')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.PositiveIntegerField(default=0, help_text='هرچه عدد بزرگ\u200cتر باشد، قانون اختصاصی\u200cتر/مهم\u200cتر در نظر گرفته می\u200cشود.', verbose_name='اولویت')),
                ('requirement_level', models.CharField(choices=[('general', 'عمومی'), ('country', 'مخصوص کشور'), ('cargo_type', 'مخصوص دسته کالا'), ('cargo_subcategory', 'مخصوص زیردسته کالا'), ('custom', 'سفارشی')], default='general', max_length=30, verbose_name='سطح قانون')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت داخلی ادمین')),
                ('customer_description', models.TextField(blank=True, verbose_name='توضیح قابل نمایش به مشتری')),
                ('cargo_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='rates.cargosubcategory', verbose_name='زیردسته کالا')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='rates.cargotype', verbose_name='دسته اصلی کالا')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='locations.country', verbose_name='کشور مقصد')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='documents.documenttype', verbose_name='نوع مدرک')),
            ],
            options={
                'verbose_name': 'قانون مدرک',
                'verbose_name_plural': 'قوانین مدارک',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.models.order_document_upload_to, verbose_name='فایل')),
                ('status', models.CharField(choices=[('pending_upload', 'در انتظار آپلود'), ('uploaded', 'آپلود شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending_upload', max_length=30, verbose_name='وضعیت')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیح مشتری')),
                ('forwarder_note', models.TextField(blank=True, verbose_name='توضیح فورواردر')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_documents', to='documents.documenttype', verbose_name='نوع مدرک')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='orders.cargorequest', verbose_name='سفارش')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_order_documents', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents.documentrule', verbose_name='قانون ایجادکننده')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_documents', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'مدرک سفارش',
                'verbose_name_plural': 'مدارک سفارش',
                'ordering': ['document_type__title'],
            },
        ),
        migrations.AddIndex(
            model_name='documentrule',
            index=models.Index(fields=['shipping_procedure'], name='documents_d_shippin_20359c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrule',
            index=models.Index(fields=['transport_mode'], name='documents_d_transpo_7c4bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrule',
            index=models.Index(fields=['is_active'], name='documents_d_is_acti_61d8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrule',
            index=models.Index(fields=['is_required'], name='documents_d_is_requ_bb293c_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdocument',
            constraint=models.UniqueConstraint(fields=('order', 'document_type'), name='unique_document_type_per_order'),
        ),
    ]
