# Generated by Django 6.0.1 on 2026-06-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('locations', '0004_alter_port_port_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrule',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='locations.destinationcity', verbose_name='شهر مقصد'),
        ),
        migrations.AddField(
            model_name='documentrule',
            name='destination_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='locations.port', verbose_name='پورت/فرودگاه/گمرک مقصد'),
        ),
        migrations.AddField(
            model_name='documentrule',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='locations.city', verbose_name='شهر مبدا'),
        ),
        migrations.AddField(
            model_name='documentrule',
            name='origin_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_rules', to='locations.province', verbose_name='استان مبدا'),
        ),
        migrations.AlterField(
            model_name='documentrule',
            name='requirement_level',
            field=models.CharField(choices=[('general', 'عمومی'), ('shipping_procedure', 'بر اساس رویه ارسال'), ('destination', 'بر اساس مقصد'), ('origin', 'بر اساس مبدا'), ('transport_mode', 'بر اساس روش حمل'), ('cargo_type', 'بر اساس دسته کالا'), ('cargo_subcategory', 'بر اساس زیردسته کالا'), ('custom', 'سفارشی')], default='general', max_length=30, verbose_name='سطح قانون'),
        ),
    ]
