# Generated by Django 6.0.1 on 2026-06-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentrule_destination_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldocumentrequest',
            name='is_read_by_customer',
            field=models.BooleanField(default=False, verbose_name='خوانده شده توسط مشتری'),
        ),
    ]
