# Generated by Django 6.0.1 on 2026-09-14 08:40

import core.storage
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_is_read_by_customer_to_additionaldocumentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocumentupload',
            name='file',
            field=models.FileField(storage=core.storage.protected_storage, upload_to=documents.models.additional_document_upload_to, verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.protected_storage, upload_to=documents.models.order_document_upload_to, verbose_name='فایل'),
        ),
    ]
