# Generated by Django 6.0.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_additionaldocumentupload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdocument',
            name='status',
            field=models.CharField(choices=[('pending_upload', 'در انتظار آپلود'), ('uploaded', 'آپلود شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending_upload', max_length=30, verbose_name='وضعیت'),
        ),
    ]
