# Generated by Django 6.0.1 on 2026-06-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port_type',
            field=models.CharField(choices=[('sea', 'بندر دریایی'), ('air', 'فرودگاه'), ('land ', 'گمرک زمینی'), ('rail ', 'گمرک زمینی')], max_length=5),
        ),
    ]
