# Generated by Django 6.0.1 on 2026-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_port_port_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port_type',
            field=models.CharField(choices=[('sea', 'بندر'), ('air', 'فرودگاه'), ('land', 'گمرک زمینی'), ('rail', 'گمرک ریلی')], max_length=5),
        ),
    ]
