# Generated by Django 6.0.1 on 2026-06-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_port_port_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='locations.country', verbose_name='کشور'),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'name')},
        ),
    ]
