# Generated by Django 6.0.1 on 2026-06-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_set_iran_for_existing_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='locations.country', verbose_name='کشور'),
        ),
    ]
