# Generated by Django 6.0.1 on 2026-06-06 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_alter_port_port_type'),
        ('rates', '0005_rate_cargo_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_mode', models.CharField(choices=[('air', 'هوایی'), ('sea_fcl', 'دریایی FCL'), ('sea_lcl', 'دریایی LCL'), ('land', 'زمینی'), ('rail', 'ریلی')], max_length=20, verbose_name='روش حمل درخواست\u200cشده')),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='وزن واقعی (KG)')),
                ('chargeable_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='وزن قابل پرداخت (Chargeable)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت نهایی محاسبه شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید فورواردر'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.cargotype', verbose_name='نوع کالا')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_requests', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.port', verbose_name='پورت/فرودگاه مقصد')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city', verbose_name='شهر مبدا')),
                ('selected_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='rates.rate', verbose_name='نرخ انتخاب شده فورواردر')),
            ],
            options={
                'verbose_name': 'درخواست حمل',
                'verbose_name_plural': 'درخواست\u200cهای حمل',
            },
        ),
        migrations.CreateModel(
            name='CargoDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='طول (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='عرض (cm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ارتفاع (cm)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('cargo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='orders.cargorequest')),
            ],
            options={
                'verbose_name': 'ابعاد کالا',
                'verbose_name_plural': 'ابعاد کالاها',
            },
        ),
    ]
