# Generated by Django 6.0.1 on 2026-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='container_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کانتینر'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='container_size',
            field=models.CharField(blank=True, choices=[('20ft', '۲۰ فوت'), ('40ft_std', '۴۰ فوت استاندارد'), ('40ft_hc', '۴۰ فوت های\u200cکیوب'), ('45ft_hc', '۴۵ فوت های\u200cکیوب')], max_length=20, null=True, verbose_name='ابعاد کانتینر'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='container_type',
            field=models.CharField(blank=True, choices=[('dry', 'خشک استاندارد'), ('reefer', 'یخچالی'), ('open_top', 'روباز از بالا'), ('flat_rack', 'تخت'), ('platform', 'پلتفرم'), ('tank', 'تانکی'), ('ventilated', 'دارای تهویه'), ('insulated', 'عایق\u200cبندی\u200cشده'), ('double_door', 'دو درب')], max_length=20, null=True, verbose_name='نوع کانتینر'),
        ),
    ]
