# Generated by Django 6.0.1 on 2026-06-07 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_port_port_type'),
        ('orders', '0002_cargorequest_container_count_and_more'),
        ('rates', '0006_alter_cargotype_options_alter_cargotype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='cargo_subcategories',
            field=models.ManyToManyField(blank=True, related_name='requests', to='rates.cargosubcategory', verbose_name='زیردسته\u200cهای کالا'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='other_cargo_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سایر جزئیات کالا (در صورت نبود در لیست)'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='sender_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دقیق پستی فرستنده'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='sender_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_city_requests', to='locations.city', verbose_name='شهر فرستنده'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='sender_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_requests', to='locations.province', verbose_name='استان فرستنده'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='cargo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.cargotype', verbose_name='نوع کالا (دسته اصلی)'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_requests', to='locations.city', verbose_name='شهر مبدا'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس (نیاز به تکمیل اطلاعات)'), ('pending', 'در انتظار تایید فورواردر'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='draft', max_length=20, verbose_name='وضعیت درخواست'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='فیلد تغییر یافته')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='مقدار جدید')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت / پیام')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر تغییر دهنده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.cargorequest', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'تاریخچه سفارش',
                'verbose_name_plural': 'تاریخچه سفارشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
