# Generated by Django 6.0.1 on 2026-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cargorequest_cargo_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی فرستنده'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='sender_national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی فرستنده'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس فرستنده'),
        ),
    ]
