# Generated by Django 6.0.1 on 2026-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cargorequest_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='shipping_procedure',
            field=models.CharField(choices=[('passenger', 'مسافری'), ('commercial', 'تجاری')], default='commercial', max_length=20, verbose_name='رویه ارسال'),
        ),
    ]
