# Generated by Django 6.0.1 on 2026-06-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_province_country'),
        ('orders', '0005_cargorequest_shipping_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='base_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه حمل'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='doorstep_packaging_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه تحویل و بسته\u200cبندی درب محل'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_requests', to='locations.country', verbose_name='کشور مبدا'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='origin_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_requests', to='locations.province', verbose_name='استان مبدا'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='packaging_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه بسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='price_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='جمع قبل از ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مبلغ ارزش افزوده'),
        ),
    ]
