# Generated by Django 6.0.1 on 2026-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cargorequest_base_shipping_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='needs_doorstep_packaging',
            field=models.BooleanField(default=False, verbose_name='نیاز به بسته\u200cبندی و تحویل در محل'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='needs_packaging',
            field=models.BooleanField(default=False, verbose_name='نیاز به بسته\u200cبندی'),
        ),
    ]
