# Generated by Django 6.0.1 on 2026-06-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cargorequest_needs_doorstep_packaging_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargorequest',
            name='needs_packaging',
        ),
        migrations.RemoveField(
            model_name='cargorequest',
            name='packaging_price',
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='needs_office_packaging',
            field=models.BooleanField(default=False, verbose_name='نیاز به بسته\u200cبندی در دفتر'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='needs_onsite_packaging',
            field=models.BooleanField(default=False, verbose_name='نیاز به بسته\u200cبندی در محل'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='office_packaging_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه بسته\u200cبندی در دفتر'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='onsite_packaging_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه بسته\u200cبندی در محل'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='doorstep_packaging_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه حمل و بسته\u200cبندی در محل'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='needs_doorstep_packaging',
            field=models.BooleanField(default=False, verbose_name='نیاز به حمل و بسته\u200cبندی در محل'),
        ),
    ]
