# Generated by Django 6.0.1 on 2026-06-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cargorequest_needs_packaging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargorequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس (نیاز به تکمیل اطلاعات)'), ('pending', 'در انتظار تایید فورواردر'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
