# Generated by Django 6.0.1 on 2026-06-22 01:23

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cargorequest_status'),
        ('rates', '0013_cargosubcategorychild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargorequest',
            name='sender_national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[core.validators.validate_iranian_national_code], verbose_name='کد ملی فرستنده'),
        ),
        migrations.CreateModel(
            name='OrderCargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_other', models.BooleanField(default=False, verbose_name='گزینه سایر انتخاب شده')),
                ('other_child_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن سایر (در صورت انتخاب سایر)')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='rates.cargosubcategorychild', verbose_name='فرزند زیردسته')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='orders.cargorequest', verbose_name='سفارش')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='rates.cargosubcategory', verbose_name='زیردسته کالا')),
            ],
            options={
                'verbose_name': 'قلم کالای سفارش',
                'verbose_name_plural': 'اقلام کالای سفارش',
            },
        ),
    ]
