# Generated by Django 6.0.1 on 2026-06-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cargorequest_sender_national_id_ordercargoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('doc_request', 'درخواست مدرک جدید'), ('order_status', 'تغییر وضعیت سفارش'), ('doc_status', 'تغییر وضعیت مدرک'), ('message', 'پیام جدید از فورواردر')], max_length=20, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='زیرعنوان')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notifications', to='orders.cargorequest', verbose_name='سفارش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان مشتری',
                'verbose_name_plural': 'اعلان\u200cهای مشتری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_role', models.CharField(choices=[('customer', 'مشتری'), ('forwarder', 'فورواردر')], max_length=20, verbose_name='نقش فرستنده')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('is_read_by_customer', models.BooleanField(default=False, verbose_name='خوانده شده توسط مشتری')),
                ('is_read_by_forwarder', models.BooleanField(default=False, verbose_name='خوانده شده توسط فورواردر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.cargorequest', verbose_name='سفارش')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_order_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام سفارش',
                'verbose_name_plural': 'پیام\u200cهای سفارش',
                'ordering': ['created_at'],
            },
        ),
    ]
