# Generated by Django 6.0.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_forwarder_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargorequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس (نیاز به تکمیل اطلاعات)'), ('pending', 'در انتظار تایید فورواردر'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت درخواست'),
        ),
    ]
